### PR TITLE
Reword introduction to the event.

### PR DESCRIPTION
**Pull request by mjtamlyn**
- No mention of technical talks or experienced developers
- Mention that not all organisers are core
- Move end of sprint day 2 to 2pm.

### CODE REVIEW

**Comment by erikr** [comment]
Does `members of the core team and friends` not make non-core members sound secondary? I honestly don't know. I think it is useful to mention that core team members are involved as it adds legitimacy, especially for sponsors.

Otherwise, :shipit:

**Comment by olasitarska** [comment]
Agreed with Erik!

Thanks for doing it!

**Comment by mjtamlyn** [comment]
How about `members of the Django community, including several members of the core team`?

**Comment by erikr** [comment]
:+1: :100: :shipit:

**Comment by mjtamlyn** [comment]
:shipit:

**Pull request merged**
